### ISSUE TITLE
Language ms not suported for alignment. Skipping this step Formatting segments...ERROR !!!

### ISSUE THREAD

**Issue by TdiasT23** [matheusbach/legen#11]
Prezados, está ocorrendo este erro em todos os videos que tento legendar.
O pode ser...?

**Comment by matheusbach** [comment]
Algumas linguagens não são suportadas pelos modelos de alinhamento cadastrados, portando, essa etapa é pulada, restando somente o alinhamento original.

Adicionalmente, verifique se a lingua detectada está correta. As vezes, vídeos com muita música ou sem voz são detectados erroneamente. Caso esse seja seu caso, force a linguagem de entrada com --input_lang [lang]
