### ISSUE TITLE
traducao congela - wsl2 ubuntu 22.04

### ISSUE THREAD

**Issue by yakkobr** [matheusbach/legen#14]
**comando:**
python3 legen.py -i legenda/ --input_lang en --translate=pt_BR -ts:m large --disable_hardsubs
***************************************************************************

**execução/retorno:**
legen v0.16 - github.com/matheusbach/legen
python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]

Loading whisperx model: large-v3 (auto) on cuda
/home/suporte/.local/lib/python3.10/site-packages/pyannote/audio/core/io.py:43: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
/home/suporte/.local/lib/python3.10/site-packages/torch_audiomentations/utils/io.py:27: UserWarning: torchaudio._backend.set_audio_backend has been deprecated. With dispatcher enabled, this function is no-op. You can remove the function call.
  torchaudio.set_audio_backend("soundfile")
torchvision is not available - cannot save figures
No language specified, language will be first be detected for each audio file (increases inference time).
Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.0.3. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint --file ../.cache/torch/whisperx-vad-segmentation.bin`
Model was trained with pyannote.audio 0.0.1, yours is 3.1.1. Bad things might happen unless you revert pyannote.audio to 0.x.
Model was trained with torch 1.10.0+cu102, yours is 2.2.1+cu121. Bad things might happen unless you revert torch to 1.x.
⏱ Took 13s

Processing 9 - Deploying Your Web App on Azure/51 - Source Code.html
not a video file
⌚ Done in 0s

Processing 9 - Deploying Your Web App on Azure/52 - Bonus Lesson.html
not a video file
⌚ Done in 0s

Processing 1 - Introduction/1 - Introduction.mp4
Forced input audio language: en
Transcription is unnecessary. Skipping.
Translating with Google Translate
Translating   0% | 0/9 | ETA: ? | ⏱: 00:00

**Comment by matheusbach** [comment]
this issue is related to #12?

**Comment by yakkobr** [comment]
> this issue is related to #12?

Não, é outro problema.

**Comment by ecodelearn** [comment]
muda o codigo @yakkobr 
python3 legen.py -i legenda/ --input_lang en --translate=pt_BR -ts:m large --disable_hardsubs
para:
python3 legen.py -i legenda/ --input_lang en --translate=pt -ts:m large --disable_hardsubs

ref: https://cloud.google.com/translate/docs/languages?hl=pt-br

**Comment by matheusbach** [comment]
> muda o codigo @yakkobr python3 legen.py -i legenda/ --input_lang en --translate=pt_BR -ts:m large --disable_hardsubs para: python3 legen.py -i legenda/ --input_lang en --translate=pt -ts:m large --disable_hardsubs
> 
> ref: https://cloud.google.com/translate/docs/languages?hl=pt-br

Isso mesmo. Não há diferenciação do pt-pt para pt-br na API do google translate. É tudo pt
