### ISSUE TITLE
Problem with legen styling

### ISSUE THREAD

**Issue by paraoxy** [matheusbach/legen#16]
Hi.

I tried installing:
https://github.com/NelsonJQ/legen-styles
on Google Colab

and I set the styling i wanted and all perfect, until i executed the last operation, i got this:

LeGen: error: unrecognized arguments: --srt_out_dir /content/drive/MyDrive/LeGen/softsubs --burned_out_dir /content/drive/MyDrive/LeGen/hardsubs --only_video --disable_embed --whisperx --dev cuda --model medium --compute_type default --batch_size 12 --lang ar --sub_style Tahoma,PrimaryColour=&H00FFFFFF,Fontsize=12,Borderstyle=4,BackColour=&H80000000,Bold=1,Spacing=0.4,Outline=1,Shadow=0,MarginL=10,MarginR=10,MarginV=252

why is this??

**Comment by matheusbach** [comment]
Hi. This issue should be opened in fork repo. Probably the fork doesn't updated the colab notebook when updated software parameters
