### ISSUE TITLE
Execution Problems: TF-TRT Warning: Could not find TensorRT and ERROR !!!

### ISSUE THREAD

**Issue by HPGJunior** [matheusbach/legen#5]
Estava utilizando normalmente sua aplicação, porém de alguns dias para cá comecei a receber a seguinte mensagem ao executar !python3 legen.py -i "/content/drive/MyDrive/legen/..." --only_srt_subtitles --disable_burn --disable_embed --model large-v2 --dev cuda --srt_out_dir "/content/drive/MyDrive/legen/PROJETOS/SRTS":

2023-09-28 01:29:32.353770: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

E em seguinda o processo se inicia, porém ao final recebo essa mensagem:

ERROR !!! /content/drive/MyDrive/legen/.../arquivo.mp4
check legen-errors.txt for details

O que pode ser? Me desculpe por esse incomodo, mas não tenho conhecimento algum. Por favor, me ajude!

PS: Tento sempre executar em T4 GPU, pois fui orientado assim.

Obrigado!!

I was using your application normally, but a few days ago I started receiving the following message when executing !python3 legen.py -i "/content/drive/MyDrive/legen/..." --only_srt_subtitles --disable_burn --disable_embed --model large-v2 --dev cuda --srt_out_dir "/content/drive/MyDrive/legen/PROJETOS/SRTS":

2023-09-28 01:29:32.353770: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

And then the process starts, but at the end I receive this message:

ERROR!!! /content/drive/MyDrive/legen/.../arquivo.mp4
check legen-errors.txt for details

What can it be? I'm sorry for this inconvenience, but I have no knowledge. Please help me!

PS: I always try to run on T4 GPU, as I was guided that way.

Thanks!!

**Comment by matheusbach** [comment]
Acredito que o aviso inicial não tenha relação com o erro. De qualquer forma, para suprimir o aviso, instale o tensorrt usando ```pip install tensorrt```

Anexe o arquivo ```legen-errors.txt``` para que eu possa entender a causa real do erro
