### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by Cybasaint** [matheusbach/legen#6]
I keep getting this error 

python legen.py -i "H:\legen-main\test" --model medium --dev cpu --lang en --srt_out_dir "H:\legen-main\test"

This is the command I run. 

Error log says  H:/legen-main/test/01.mp4: FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by matheusbach** [comment]
Verify if ffmpeg and all dependencies is correctly instaled and added to windows PATH

**Comment by Cybasaint** [comment]
Thank you I think I had an exFat drive which wasnt giving permission, converted to ntfs and it seems to work fine now!
