### ISSUE TITLE
Erro DISPLAY

### ISSUE THREAD

**Issue by c3techweb** [matheusbach/legen#7]
Conseguem me ajudar a resolver esse erro? 

TclError: no display name and no $DISPLAY environment variable

**Comment by matheusbach** [comment]
Esse erro acontece quando você tenta rodar o LeGen em um ambiente sem nenhum monitor. Durante o processo da formatação das legendas, o software simula uma renderização para encontrar o tamanho que a legenda ocupa na tela.

Para corrigir o erro: https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable

Caso use Colab, use o [notebook oficial do LeGen](https://colab.research.google.com/github/matheusbach/legen/blob/main/legen.ipynb), que aplica essa correção
