### ISSUE TITLE
Some files are not transcoding! 

### ISSUE THREAD

**Issue by booiggers** [matheusbach/legen#8]
I have a folder with entire course with mp4 files. It has file names such as 03-1. Orientation 03-2. Orientation etc but it only transcode one of the mp4 03-1, 06-2, 09-1 etc I had to put those missing mp4 in separate folder to redo it again. The other file names which has a single number like 01. Design 02. Practice such files do it if it has two parts like the examples, it takes only one of those videos.

**Comment by matheusbach** [comment]
Please sent the full name of those files, so I can reproduce the behavior on my side
