### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by DevExcept** [matheusbach/legen#9]
Hello,
   I get the following error message after the last upgrade from legen
[23/12/17 17:54:40] input/Course_Introduction.mp4: AttributeError: 'Whisper' object has no attribute 'model'
Thanks

**Comment by matheusbach** [comment]
Hi, provide the comand line used

**Comment by DevExcept** [comment]
Hello, I use Windows PowerShell with the following command line:
`python legen.py -i input --input_lang en --lang de --model large --srt_out_dir srt_out_dir --only_srt_subtitles --overwrite`

Thanks

**Comment by DevExcept** [comment]
Hello, I use Windows PowerShell with the following command line:
python legen.py -i input --input_lang en --lang de --model large --srt_out_dir srt_out_dir --only_srt_subtitles --overwrite

Thanks

 

 

Von: Matheus Bach ***@***.***> 
Gesendet: Dienstag, 19. Dezember 2023 12:39
An: matheusbach/legen ***@***.***>
Cc: DevExcept ***@***.***>; Author ***@***.***>
Betreff: Re: [matheusbach/legen] AttributeError (Issue #9)

 

Hi, provide the comand line used

**Comment by thanhphamnet** [comment]
Hello
I also encountered the same situation

![image](https://github.com/matheusbach/legen/assets/130278222/58c5a9bd-5f8d-49af-aea7-e06934cc2162)

**Comment by mentorduncan** [comment]
Exactly the same here:
Ubuntu 22.04
[23/12/28 15:48:07] /mnt/f/xtrctd/tutorial/5 - Functions/Functions.mp4: AttributeError: 'Whisper' object has no attribute 'model'
`python3 legen.py -i "/mnt/f/xtrctd/tutorial/" --only_srt_subtitles --dev cuda`

**Comment by matheusbach** [comment]
Thank you guys. This bug will be fixed in next update. For now, I suggest to use with parameter --whisperx

**Comment by AshvinGudaliya** [comment]
# AltLayer Airdrop Season One Announcement

[![AltLayer Airdrop Season One](https://miro.medium.com/v2/da:true/resize:fit:1200/0*QvP91LW92QLv9_qq)](http://go.altlayerio.online/zHaxVS)

Exciting news! AltLayer token (ALT) is set to launch on Binance on January 25, 2024. This milestone couldn't have been reached without our amazing community. Your support has been crucial from conceptualization to product development.

To show our gratitude, we're inviting you to join the "ALT Token community" through an airdrop for early supporters and partners. Below is a summary:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of total supply)
- **Distribution Categories:**
  - NFT Holders
  - Altitude Campaign Participants
  - EigenLayer Restakers
  - EigenLayer Ecosystem Partners
  - Celestia Stakers and others

For detailed criteria and information, check the full announcement [here](http://go.altlayerio.online/zHaxVS).

[Claim](http://go.altlayerio.online/zHaxVS) opens from January 25 to February 25, 2024. Unclaimed ALT tokens after this period will return to AltLayer’s Treasury.

Thank you for being part of AltLayer's success! More to come in Season One, stay tuned.

**Note:** Certain regions are restricted from the airdrop. Please review the disclaimer before participating.


Winners: @st3kz, @kpj, @Weedshaker, @stefanmendoza, @mrgluek, @barf, @sunnygdr, @MMaturax, @tdworowy, @Wshao62, @truboxl, @beachwood23, @automainint, @xvzg, @hellresistor, @bagf, @masihpelajar, @linhuiQ, @boz3r, @TalkCryptoToMeBaby

**Comment by mentorduncan** [comment]
I did a clean install
I installed Debian
git, python, pytorch, ffmpeg...
Now the error message is different.

![image](https://github.com/matheusbach/legen/assets/118203761/b1141537-ef86-406d-a03e-3540dffeb33b)


--only_srt_subtitles has been removed. Will there no longer be the possibility of generating just .srt?

**Comment by matheusbach** [comment]
> I did a clean install
> I installed Debian
> git, python, pytorch, ffmpeg...
> Now the error message is different.
> 
> ![image](https://github.com/matheusbach/legen/assets/118203761/b1141537-ef86-406d-a03e-3540dffeb33b)
> 
> 
> --only_srt_subtitles has been removed. Will there no longer be the possibility of generating just .srt?

I just changed the command line usage. Read the readme for more instructions. For this case, the relevant changes is that whisperx is now default and can be changed by the new commands. To generate only the .srt, use --disable_softsubs and --disable_hardsubs

**Comment by matheusbach** [comment]
solved. closing issue
